### ISSUE TITLE
Can you give an example when i wanna to use the correlation matrix that i create?

### ISSUE THREAD

**Issue by keyalone** [JINJINT/ESCO#1]

**Comment by keyalone** [comment]
The corr paramater in escoSimulateGroups function was set to the correlation matrix i created. I got the different ones in metadata(sim)$Params.

**Comment by JINJINT** [comment]
Hi,

Thanks for reaching out! I think you are using code correctly but the
output needs a further step to interpret:

The trickiness here is, during the process of using the correlation matrix
you created when generating cells of different groups, the correlation
matrixes are rearranged in order to match the marginal expression level
(since there is more heterogeneity comparing with just one cell type. The
rearrangement is done by assuming that your given correlation matrixes are
ordered corresponding to gene mean expression (from larger to small). You
could refer to these lines of source code
<https://github.com/JINJINT/ESCO/blob/e3aa5d61220d537e33a92b0cc472546af50774d9/R/esco-simulate.R#L1037>
to see how exactly the rearrangement is done.)

So you should try to sort the simulated DE genes based on their mean gene
expression level, and that should give you the correlation matrix alike
your original input. (If I remember correctly.)

Sincerely sorry that I did not explain this very clear in the vignette. (I
will add it soon.) So thanks for bringing this up, and if you have further
questions, feel free to let me know!

Best,
Jinjin

**Comment by keyalone** [comment]
Thank you very much for your reply.
